import { z } from "zod";

export const PlantSchema = z.object({
  commonName: z.string().nullable(),
  latinName: z.string().nullable(),
  light: z.string().nullable(),
  lightLevel: z.enum(["low", "medium", "high"]).nullable().optional(),
  water: z.string().nullable(),
  careTips: z.array(z.string()).default([]),
  warnings: z.array(z.string()).default([]),
  confidence: z.string().nullable(),
  tags: z
    .array(
      z.enum([
        // Plant Type
        "fruit-tree",
        "ornamental-tree",
        "evergreen-tree",
        "deciduous-shrub",
        "evergreen-shrub",
        "flowering-shrub",
        "shade-perennial",
        "sun-perennial",
        "ornamental-grass",
        "ground-cover",
        "climbing-vine",
        "annual-flower",
        "tropical-annual",
        "bulb",
        "fern",
        "hosta",
        "rose",
        "rhododendron",
        "azalea",
        "hydrangea",
        "lavender",
        "herb",
        "vegetable-starts",
        "tomato",
        "berry-bush",
        "succulent",
        "houseplant",
        "bonsai",
        "water-plant",
        "edible-flower",
        // Light
        "full-sun-plant",
        "part-shade-plant",
        "full-shade-plant",
        "adaptable-light",
        // Water
        "drought-tolerant",
        "moderate-water",
        "high-water",
        "moisture-lover",
        // Seasonal
        "spring-bloomer",
        "summer-bloomer",
        "fall-bloomer",
        "winter-interest",
        "spring-ephemeral",
        "deciduous",
        "evergreen",
        // Care Complexity
        "beginner-friendly",
        "intermediate-care",
        "expert-care",
        // Pest & Disease
        "slug-risk",
        "aphid-risk",
        "powdery-mildew-risk",
        "deer-risk",
        "root-rot-risk",
        "virus-risk",
        "scale-risk",
        // Container
        "container-friendly",
        "needs-ground-space",
        "raised-bed-ideal",
        "hanging-basket",
        // PNW Specific
        "pnw-native",
        "pnw-adapted",
        "rain-tolerant",
        "heat-sensitive",
        "frost-tender",
        "winter-hardy",
        // Upsell
        "needs-fertilizer-spring",
        "needs-fertilizer-fall",
        "needs-pruning-tools",
        "needs-support-structure",
        "needs-soil-amendment",
        "needs-pest-control",
        "needs-mulch",
        "pot-upgrade-candidate",
        "companion-planting-opportunity",
      ]),
    )
    .optional(),
});

export type PlantInfo = z.infer<typeof PlantSchema>;
